spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db
    username: my_user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect